# wrangler.toml
name = "gemini-proxy-panel"
main = "worker/src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]


[assets]
binding = "ASSETS"
directory = "public"

[observability]
enabled = true

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "f1b79d3fd5ee44c4bb540deeab96ba5a"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "f2894ba2fa71438a93562d7c5a9ed506"

